// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/planes": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/signup/:stepSlug": {
    params: {
      "stepSlug": string;
    };
  };
  "/auth/:provider": {
    params: {
      "provider": string;
    };
  };
  "/auth/callback/:provider": {
    params: {
      "provider": string;
    };
  };
  "/dash": {
    params: {};
  };
  "/dash/perfil": {
    params: {};
  };
  "/dash/agenda": {
    params: {};
  };
  "/dash/onboarding": {
    params: {};
  };
  "/dash/servicios": {
    params: {};
  };
  "/dash/servicios/nuevo": {
    params: {};
  };
  "/dash/servicios/:serviceId": {
    params: {
      "serviceId": string;
    };
  };
  "/dash/servicios/:serviceId/general": {
    params: {
      "serviceId": string;
    };
  };
  "/dash/servicios/:serviceId/agendamiento": {
    params: {
      "serviceId": string;
    };
  };
  "/dash/servicios/:serviceId/horario": {
    params: {
      "serviceId": string;
    };
  };
  "/dash/servicios/:serviceId/cobros": {
    params: {
      "serviceId": string;
    };
  };
  "/dash/website": {
    params: {};
  };
  "/dash/clientes/:email": {
    params: {
      "email": string;
    };
  };
  "/dash/clientes": {
    params: {};
  };
  "/dash/lealtad": {
    params: {};
  };
  "/dash/evaluaciones": {
    params: {};
  };
  "/dash/evaluaciones/:serviceId": {
    params: {
      "serviceId": string;
    };
  };
  "/dash/ajustes": {
    params: {};
  };
  "/dash/pagos": {
    params: {};
  };
  "/api/customers": {
    params: {};
  };
  "/api/services": {
    params: {};
  };
  "/api/employees": {
    params: {};
  };
  "/api/events": {
    params: {};
  };
  "/api/org": {
    params: {};
  };
  "/api/domain": {
    params: {};
  };
  "/stripe": {
    params: {};
  };
  "/demo/smatch": {
    params: {};
  };
  "/:serviceSlug": {
    params: {
      "serviceSlug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/planes" | "/signin" | "/signup" | "/signup/:stepSlug" | "/auth/:provider" | "/auth/callback/:provider" | "/dash" | "/dash/perfil" | "/dash/agenda" | "/dash/onboarding" | "/dash/servicios" | "/dash/servicios/nuevo" | "/dash/servicios/:serviceId" | "/dash/servicios/:serviceId/general" | "/dash/servicios/:serviceId/agendamiento" | "/dash/servicios/:serviceId/horario" | "/dash/servicios/:serviceId/cobros" | "/dash/website" | "/dash/clientes/:email" | "/dash/clientes" | "/dash/lealtad" | "/dash/evaluaciones" | "/dash/evaluaciones/:serviceId" | "/dash/ajustes" | "/dash/pagos" | "/api/customers" | "/api/services" | "/api/employees" | "/api/events" | "/api/org" | "/api/domain" | "/stripe" | "/demo/smatch" | "/:serviceSlug";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/planes.tsx": {
    id: "routes/planes";
    page: "/planes";
  };
  "routes/login/signin.tsx": {
    id: "routes/login/signin";
    page: "/signin";
  };
  "routes/login/signup._index.tsx": {
    id: "routes/login/signup._index";
    page: "/signup";
  };
  "routes/login/signup.$stepSlug.tsx": {
    id: "routes/login/signup.$stepSlug";
    page: "/signup/:stepSlug";
  };
  "routes/auth.$provider.tsx": {
    id: "routes/auth.$provider";
    page: "/auth/:provider";
  };
  "routes/auth.callback.$provider.tsx": {
    id: "routes/auth.callback.$provider";
    page: "/auth/callback/:provider";
  };
  "routes/dash/dash_layout.tsx": {
    id: "routes/dash/dash_layout";
    page: "/dash" | "/dash/perfil" | "/dash/agenda" | "/dash/onboarding" | "/dash/servicios" | "/dash/servicios/nuevo" | "/dash/servicios/:serviceId" | "/dash/servicios/:serviceId/general" | "/dash/servicios/:serviceId/agendamiento" | "/dash/servicios/:serviceId/horario" | "/dash/servicios/:serviceId/cobros" | "/dash/website" | "/dash/clientes/:email" | "/dash/clientes" | "/dash/lealtad" | "/dash/evaluaciones" | "/dash/evaluaciones/:serviceId" | "/dash/ajustes" | "/dash/pagos";
  };
  "routes/dash/dash._index.tsx": {
    id: "routes/dash/dash._index";
    page: "/dash";
  };
  "routes/dash/dash.profile.tsx": {
    id: "routes/dash/dash.profile";
    page: "/dash/perfil";
  };
  "routes/dash/dash.agenda.tsx": {
    id: "routes/dash/dash.agenda";
    page: "/dash/agenda";
  };
  "routes/dash/dash.onboarding.tsx": {
    id: "routes/dash/dash.onboarding";
    page: "/dash/onboarding";
  };
  "routes/dash/servicios/index.tsx": {
    id: "routes/dash/servicios/index";
    page: "/dash/servicios";
  };
  "routes/dash/servicios/new.tsx": {
    id: "routes/dash/servicios/new";
    page: "/dash/servicios/nuevo";
  };
  "routes/dash/servicios/dash.servicios_.$serviceId.tsx": {
    id: "routes/dash/servicios/dash.servicios_.$serviceId";
    page: "/dash/servicios/:serviceId";
  };
  "routes/dash/servicios/dash.servicios_.$serviceId_.general.tsx": {
    id: "routes/dash/servicios/dash.servicios_.$serviceId_.general";
    page: "/dash/servicios/:serviceId/general";
  };
  "routes/dash/servicios/dash.servicios_.$serviceId_.agendamiento.tsx": {
    id: "routes/dash/servicios/dash.servicios_.$serviceId_.agendamiento";
    page: "/dash/servicios/:serviceId/agendamiento";
  };
  "routes/dash/servicios/dash.servicios_.$serviceId_.horario.tsx": {
    id: "routes/dash/servicios/dash.servicios_.$serviceId_.horario";
    page: "/dash/servicios/:serviceId/horario";
  };
  "routes/dash/servicios/dash.servicios_.$serviceId_.cobros.tsx": {
    id: "routes/dash/servicios/dash.servicios_.$serviceId_.cobros";
    page: "/dash/servicios/:serviceId/cobros";
  };
  "routes/dash/website/dash.website.tsx": {
    id: "routes/dash/website/dash.website";
    page: "/dash/website";
  };
  "routes/dash/dash_.clientes_.$email.tsx": {
    id: "routes/dash/dash_.clientes_.$email";
    page: "/dash/clientes/:email";
  };
  "routes/dash/dash.clientes.tsx": {
    id: "routes/dash/dash.clientes";
    page: "/dash/clientes";
  };
  "routes/dash/dash.lealtad.tsx": {
    id: "routes/dash/dash.lealtad";
    page: "/dash/lealtad";
  };
  "routes/dash/dash.reviews.tsx": {
    id: "routes/dash/dash.reviews";
    page: "/dash/evaluaciones";
  };
  "routes/dash/dash.reviews_.$serviceId.tsx": {
    id: "routes/dash/dash.reviews_.$serviceId";
    page: "/dash/evaluaciones/:serviceId";
  };
  "routes/dash/dash.ajustes.tsx": {
    id: "routes/dash/dash.ajustes";
    page: "/dash/ajustes";
  };
  "routes/dash/pagos.tsx": {
    id: "routes/dash/pagos";
    page: "/dash/pagos";
  };
  "routes/api/customers.ts": {
    id: "routes/api/customers";
    page: "/api/customers";
  };
  "routes/api/services.ts": {
    id: "routes/api/services";
    page: "/api/services";
  };
  "routes/api/employees.ts": {
    id: "routes/api/employees";
    page: "/api/employees";
  };
  "routes/api/events.ts": {
    id: "routes/api/events";
    page: "/api/events";
  };
  "routes/api/api.org.ts": {
    id: "routes/api/api.org";
    page: "/api/org";
  };
  "routes/api/api.domain.ts": {
    id: "routes/api/api.domain";
    page: "/api/domain";
  };
  "routes/stripe/api.ts": {
    id: "routes/stripe/api";
    page: "/stripe";
  };
  "routes/demo.smatch.tsx": {
    id: "routes/demo.smatch";
    page: "/demo/smatch";
  };
  "routes/service.$serviceSlug.tsx": {
    id: "routes/service.$serviceSlug";
    page: "/:serviceSlug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/planes": typeof import("./app/routes/planes.tsx");
  "routes/login/signin": typeof import("./app/routes/login/signin.tsx");
  "routes/login/signup._index": typeof import("./app/routes/login/signup._index.tsx");
  "routes/login/signup.$stepSlug": typeof import("./app/routes/login/signup.$stepSlug.tsx");
  "routes/auth.$provider": typeof import("./app/routes/auth.$provider.tsx");
  "routes/auth.callback.$provider": typeof import("./app/routes/auth.callback.$provider.tsx");
  "routes/dash/dash_layout": typeof import("./app/routes/dash/dash_layout.tsx");
  "routes/dash/dash._index": typeof import("./app/routes/dash/dash._index.tsx");
  "routes/dash/dash.profile": typeof import("./app/routes/dash/dash.profile.tsx");
  "routes/dash/dash.agenda": typeof import("./app/routes/dash/dash.agenda.tsx");
  "routes/dash/dash.onboarding": typeof import("./app/routes/dash/dash.onboarding.tsx");
  "routes/dash/servicios/index": typeof import("./app/routes/dash/servicios/index.tsx");
  "routes/dash/servicios/new": typeof import("./app/routes/dash/servicios/new.tsx");
  "routes/dash/servicios/dash.servicios_.$serviceId": typeof import("./app/routes/dash/servicios/dash.servicios_.$serviceId.tsx");
  "routes/dash/servicios/dash.servicios_.$serviceId_.general": typeof import("./app/routes/dash/servicios/dash.servicios_.$serviceId_.general.tsx");
  "routes/dash/servicios/dash.servicios_.$serviceId_.agendamiento": typeof import("./app/routes/dash/servicios/dash.servicios_.$serviceId_.agendamiento.tsx");
  "routes/dash/servicios/dash.servicios_.$serviceId_.horario": typeof import("./app/routes/dash/servicios/dash.servicios_.$serviceId_.horario.tsx");
  "routes/dash/servicios/dash.servicios_.$serviceId_.cobros": typeof import("./app/routes/dash/servicios/dash.servicios_.$serviceId_.cobros.tsx");
  "routes/dash/website/dash.website": typeof import("./app/routes/dash/website/dash.website.tsx");
  "routes/dash/dash_.clientes_.$email": typeof import("./app/routes/dash/dash_.clientes_.$email.tsx");
  "routes/dash/dash.clientes": typeof import("./app/routes/dash/dash.clientes.tsx");
  "routes/dash/dash.lealtad": typeof import("./app/routes/dash/dash.lealtad.tsx");
  "routes/dash/dash.reviews": typeof import("./app/routes/dash/dash.reviews.tsx");
  "routes/dash/dash.reviews_.$serviceId": typeof import("./app/routes/dash/dash.reviews_.$serviceId.tsx");
  "routes/dash/dash.ajustes": typeof import("./app/routes/dash/dash.ajustes.tsx");
  "routes/dash/pagos": typeof import("./app/routes/dash/pagos.tsx");
  "routes/api/customers": typeof import("./app/routes/api/customers.ts");
  "routes/api/services": typeof import("./app/routes/api/services.ts");
  "routes/api/employees": typeof import("./app/routes/api/employees.ts");
  "routes/api/events": typeof import("./app/routes/api/events.ts");
  "routes/api/api.org": typeof import("./app/routes/api/api.org.ts");
  "routes/api/api.domain": typeof import("./app/routes/api/api.domain.ts");
  "routes/stripe/api": typeof import("./app/routes/stripe/api.ts");
  "routes/demo.smatch": typeof import("./app/routes/demo.smatch.tsx");
  "routes/service.$serviceSlug": typeof import("./app/routes/service.$serviceSlug.tsx");
};