// @ts-nocheck - Types auto-generated by React Router at build time

import { useMemo, useState } from "react"
import { FaTrash } from "react-icons/fa6"
import { Form, useLoaderData } from "react-router"
import { twMerge } from "tailwind-merge"
import { getUserAndOrgOrRedirect } from "~/.server/userGetters"
import { BasicInput } from "~/components/forms/BasicInput"
import { MagnifyingGlass } from "~/components/icons/MagnifyingGlass"
import { RouteTitle } from "~/components/sideBar/routeTitle"
import { db } from "~/utils/db.server"
import type { Route } from "./+types/dash.colaboradores"
import { ClientAvatar } from "./dash.clientes"

export const loader = async ({ request }: Route.LoaderArgs) => {
  const { org } = await getUserAndOrgOrRedirect(request)
  const collaborators = await db.user.findMany({
    where: { orgId: org.id },
  })
  return { collaborators, orgName: org.name }
}

export const action = async ({ request }: Route.ActionArgs) => {
  const { org } = await getUserAndOrgOrRedirect(request)
  const formData = await request.formData()
  const intent = formData.get("intent")

  if (intent === "delete") {
    const userId = formData.get("userId") as string
    if (!userId) return { error: "userId requerido" }
    // Remove user from org by clearing orgId
    await db.user.update({
      where: { id: userId, orgId: org.id },
      data: { orgId: null },
    })
    return { ok: true }
  }

  if (intent === "invite") {
    const email = (formData.get("email") as string)?.trim()
    const displayName = (formData.get("displayName") as string)?.trim()
    if (!email) return { error: "Email requerido" }

    // Check if user already exists
    const existing = await db.user.findUnique({ where: { email } })
    if (existing) {
      if (existing.orgId === org.id) {
        return { error: "Este colaborador ya pertenece a tu organización" }
      }
      // Add existing user to org
      await db.user.update({
        where: { id: existing.id },
        data: { orgId: org.id },
      })
    } else {
      // Create new user with orgId
      await db.user.create({
        data: {
          email,
          emailVerified: false,
          displayName: displayName || null,
          orgId: org.id,
        },
      })
    }
    return { ok: true }
  }

  return { error: "Intent no reconocido" }
}

export default function Colaboradores() {
  const { collaborators } = useLoaderData<typeof loader>()
  const [search, setSearch] = useState("")
  const [showInvite, setShowInvite] = useState(false)

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase()
    if (!q) return collaborators
    return collaborators.filter(
      (c) =>
        c.displayName?.toLowerCase().includes(q) ||
        c.email?.toLowerCase().includes(q),
    )
  }, [collaborators, search])

  return (
    <>
      <RouteTitle>Colaboradores</RouteTitle>

      {/* Stats */}
      <section className="bg-white rounded-2xl p-4 sm:p-6 flex items-center justify-between">
        <div>
          <p className="text-brand_blue text-2xl font-satoMedium">
            {collaborators.length}{" "}
            {collaborators.length === 1 ? "colaborador" : "colaboradores"}
          </p>
          <p className="text-brand_gray text-sm mt-1">Miembros de tu equipo</p>
        </div>
        <button
          onClick={() => setShowInvite(!showInvite)}
          className="bg-brand_blue text-white px-4 py-2 rounded-full text-sm font-satoMedium hover:opacity-90 transition-opacity"
        >
          + Invitar
        </button>
      </section>

      {/* Invite form */}
      {showInvite && (
        <Form
          method="post"
          className="bg-white rounded-2xl p-4 sm:p-6 mt-4 flex flex-col sm:flex-row gap-3"
          onSubmit={() => setShowInvite(false)}
        >
          <input type="hidden" name="intent" value="invite" />
          <BasicInput
            name="displayName"
            placeholder="Nombre"
            containerClassName="flex-1"
          />
          <BasicInput
            name="email"
            type="email"
            placeholder="Email"
            required
            containerClassName="flex-1"
          />
          <button
            type="submit"
            className="bg-brand_blue text-white px-6 py-2 rounded-full text-sm font-satoMedium hover:opacity-90 transition-opacity self-end"
          >
            Agregar
          </button>
        </Form>
      )}

      {/* Search */}
      {collaborators.length > 0 && (
        <div className="relative w-full sm:max-w-80 my-4">
          <BasicInput
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            type="search"
            placeholder="Busca por nombre o email"
            containerClassName="w-full"
            inputClassName="!rounded-full pr-12 border-white"
          />
          <MagnifyingGlass className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 w-6 h-6 text-brand_iron" />
        </div>
      )}

      {/* Table */}
      {filtered.length > 0 && (
        <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden">
          {/* Header */}
          <div className="grid grid-cols-12 px-4 py-3 text-[12px] font-satoMedium uppercase tracking-wide text-slate-600 border-b border-slate-200">
            <span className="col-span-5 pl-2">Colaborador</span>
            <span className="col-span-3 hidden sm:block text-center">
              Email
            </span>
            <span className="col-span-2 hidden sm:block text-center">Rol</span>
            <span className="col-span-2 text-center">Acciones</span>
          </div>
          {/* Rows */}
          {filtered.map((c, i) => {
            const initials = getInitials(c.displayName, c.email)
            return (
              <div
                key={c.id}
                className={twMerge(
                  "grid grid-cols-12 items-center px-4 py-3 hover:bg-slate-50 transition-colors",
                  i < filtered.length - 1 && "border-b border-slate-100",
                )}
              >
                <div className="col-span-5 flex items-center gap-3 min-w-0">
                  <ClientAvatar
                    photoUrl={c.photoURL}
                    initials={initials}
                    size="sm"
                  />
                  <div className="min-w-0">
                    <p className="font-semibold text-brand_dark text-sm truncate">
                      {c.displayName || "—"}
                    </p>
                    <p className="text-xs text-brand_gray truncate sm:hidden">
                      {c.email}
                    </p>
                  </div>
                </div>
                <p className="col-span-3 hidden sm:block text-sm text-center text-brand_gray truncate">
                  {c.email}
                </p>
                <p className="col-span-2 hidden sm:block text-sm text-center text-brand_gray capitalize">
                  {c.role || "miembro"}
                </p>
                <div className="col-span-2 flex justify-center">
                  <Form method="post">
                    <input type="hidden" name="intent" value="delete" />
                    <input type="hidden" name="userId" value={c.id} />
                    <button
                      type="submit"
                      className="text-red-400 hover:text-red-600 p-2 rounded-full hover:bg-red-50 transition-colors"
                      title="Remover del equipo"
                    >
                      <FaTrash size={14} />
                    </button>
                  </Form>
                </div>
              </div>
            )
          })}
        </div>
      )}

      {collaborators.length === 0 && !showInvite && (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <p className="font-satoBold text-xl">Aún no tienes colaboradores</p>
          <p className="mt-2 text-brand_gray">
            Invita a tu equipo para gestionar la agenda juntos
          </p>
          <button
            onClick={() => setShowInvite(true)}
            className="mt-6 bg-brand_blue text-white px-6 py-2 rounded-full text-sm font-satoMedium hover:opacity-90 transition-opacity"
          >
            + Invitar colaborador
          </button>
        </div>
      )}

      {filtered.length === 0 && search && (
        <div className="bg-white py-16 flex flex-col items-center gap-3 text-center">
          <MagnifyingGlass className="w-12 h-12 text-brand_gray" />
          <p className="font-satoMedium text-lg">
            Sin resultados para &quot;{search}&quot;
          </p>
          <button
            onClick={() => setSearch("")}
            className="mt-2 text-brand_blue text-sm underline underline-offset-2"
          >
            Limpiar búsqueda
          </button>
        </div>
      )}
    </>
  )
}

function getInitials(displayName: string | null, email: string | null) {
  const name = (displayName || "").trim()
  if (name) {
    const parts = name.split(/\s+/).filter(Boolean)
    if (parts.length >= 2) return (parts[0][0] + parts[1][0]).toUpperCase()
    if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase()
  }
  return ((email || "").slice(0, 2) || "CO").toUpperCase()
}
